// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrzLN0BMdXCoMX9PF_2uFrx_yHFB18Meg',
    appId: '1:292002462997:web:064db5d6cd7ab205c3bd1c',
    messagingSenderId: '292002462997',
    projectId: 'healinghaven-108d9',
    authDomain: 'healinghaven-108d9.firebaseapp.com',
    storageBucket: 'healinghaven-108d9.firebasestorage.app',
    measurementId: 'G-XYVCD030TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMdF_KBee1sVqJ-4wxpJCqMaL3bv32u-c',
    appId: '1:292002462997:android:5ec9295a63c5a6e9c3bd1c',
    messagingSenderId: '292002462997',
    projectId: 'healinghaven-108d9',
    storageBucket: 'healinghaven-108d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm7RXr1Ja3C0CxU2wwmx-VWOtcOT8u_bY',
    appId: '1:292002462997:ios:731719ed04ffa201c3bd1c',
    messagingSenderId: '292002462997',
    projectId: 'healinghaven-108d9',
    storageBucket: 'healinghaven-108d9.firebasestorage.app',
    androidClientId: '292002462997-3tov5bi9fo71uue4mmrcoq3c72el1clo.apps.googleusercontent.com',
    iosClientId: '292002462997-of916dhlbh4r3o95amj04cbfq0dgo58s.apps.googleusercontent.com',
    iosBundleId: 'com.example.healingHaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm7RXr1Ja3C0CxU2wwmx-VWOtcOT8u_bY',
    appId: '1:292002462997:ios:731719ed04ffa201c3bd1c',
    messagingSenderId: '292002462997',
    projectId: 'healinghaven-108d9',
    storageBucket: 'healinghaven-108d9.firebasestorage.app',
    androidClientId: '292002462997-3tov5bi9fo71uue4mmrcoq3c72el1clo.apps.googleusercontent.com',
    iosClientId: '292002462997-of916dhlbh4r3o95amj04cbfq0dgo58s.apps.googleusercontent.com',
    iosBundleId: 'com.example.healingHaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrzLN0BMdXCoMX9PF_2uFrx_yHFB18Meg',
    appId: '1:292002462997:web:beec3d4be5cdbbdfc3bd1c',
    messagingSenderId: '292002462997',
    projectId: 'healinghaven-108d9',
    authDomain: 'healinghaven-108d9.firebaseapp.com',
    storageBucket: 'healinghaven-108d9.firebasestorage.app',
    measurementId: 'G-DEQXD5QG6C',
  );
}
